FROM mcr.microsoft.com/devcontainers/base:bullseye

RUN apt update && \
    apt install -y libcairo2-dev ffmpeg \
    texlive texlive-latex-extra texlive-fonts-extra \
    texlive-latex-recommended texlive-science \
    tipa libpango1.0-dev
